name: Setup Environment
description: Sets up Node.js environment and installs dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.0'
        
    - name: Install dependencies
      run: npm ci
      shell: bash 